### ISSUE TITLE
Mac OS X Build

### ISSUE THREAD

**Issue by eldritchideen** [uncomplicate/neanderthal-atlas#1]
I managed to get this library build on Mac OS X. 

Rather than build Atlas, OS X already ships with a tuned version called Accelerate. This is a framework, so to get the package to build I had to modify the linker options. At the moment I just hacked it in, however looking at the documentation we need to create a <profile> for each platform that can specify specific build steps. 

The only change required to get this to compile and build on my Mac was add a linker option to specify

-framework Accelerate

```
Index: pom.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- pom.xml (revision d0260c356d5cbdc0d0fe5a1e1bb61c79c0d969cb)
+++ pom.xml (revision )
@@ -95,16 +95,19 @@
                     </libraries>
                     <linker>
                         <name>g++</name>
+                        <options>
+                        <option>-framework</option>
+                        <option>Accelerate</option></options>
                         <sysLibs>
                             <sysLib>
                                 <name>c</name>
                             </sysLib>
-                            <sysLib>
+<!--                            <sysLib>
                                 <name>cblas</name>
                             </sysLib>
                             <sysLib>
                                 <name>atlas</name>
-                            </sysLib>
+                            </sysLib>-->
                         </sysLibs>
                     </linker>
                 </configuration>
```

If I get time, I will read more about how to refactor the pom file to add this in properly and do a pull request. 

The built files can be downloaded here:

https://www.dropbox.com/sh/lrjxu4mi723t0yj/AADcAqxhGF8od8XjR63XIqFma?dl=0

The mvn test target didn't seem to run the test. So I haven't tested these yet to see if they work.

**Comment by blueberry** [comment]
Hey, Steve,

Thank you very much! I was thinking about accelerate, but there are a few (important!) edge cases to check. Namely, error checking might be slightly different for accelerate and ATLAS, so we'll have to check whether the existing code works properly under accelerate (xerbla nad errprn functions).

As for the pom, we can elegantly solve the OS specificity with maven profiles.

Thank you one more time!

**Comment by blueberry** [comment]
Just a quick update: I have just built neanderthal for Mac OS X (the previously posted build was not well built). Unfortunately, Clojars does not allow me to upload it, so I'll have to wait to include it in the next release (and test it a bit more in the meantime). For now, you can download the MacOSX jar here and put it in your .m2 repository 
https://mega.nz/#!uwB10LDY!Mb_oKJf8X-C9KBQ1haNRVnKcF55cedNYYUQeie2i1HI

**Comment by blueberry** [comment]
Mac OS X support is in Clojars. Works out of the box.
